apiVersion: v1
kind: ReplicationController
metadata:
  name: users
  namespace: msprj
spec:
  replicas: 1
  selector:
    app: users
  template:
    metadata:
      name: users
      labels:
        app: users
    spec:
      containers:
      - name: users
        image: 172.25.17.4:5000/msprj/users-microservice
        ports:
        - containerPort: 9000
---
apiVersion: v1
kind: Service
metadata:
  name: users
  namespace: msprj
  labels: 
    app: users
spec:
  type: NodePort
  selector:
    app: users
  ports:
  - port: 9000
    targetPort: 9000
    nodePort: 30060

