server:
  port: 8888

eureka:
  instance:
    hostname: configserver
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/eureka/

spring:
  cloud:
    config:
      server:
        git:
          uri: @config.git.url@ 
          username: @config.git.username@
          password: @config.git.password@ 