apiVersion: v1
kind: ReplicationController
metadata:
  name: movie-ui
  namespace: @k8s.namespace@
spec:
  replicas: @spec.replicas@
  selector:
    app: movie-ui
  template:
    metadata:
      name: movie-ui
      labels:
        app: movie-ui
    spec:
      containers:
      - name: movie-ui
        image: @docker.image.prefix@/movies-ui
        ports:
        - containerPort: 9006
---
apiVersion: v1
kind: Service
metadata:
  name: movie-ui
  namespace: @k8s.namespace@
  labels: 
    app: movie-ui
spec:
  type: NodePort
  selector:
    app: movie-ui
  ports:
  - port: 9006
    targetPort: 9006
    nodePort: 31080

