apiVersion: v1
kind: ReplicationController
metadata:
  name: movie
  namespace: @k8s.namespace@
spec:
  replicas: @spec.replicas@
  selector:
    app: movie
  template:
    metadata:
      name: movie
      labels:
        app: movie
    spec:
      containers:
      - name: movie
        image: @docker.image.prefix@/movie-microservice
        ports:
        - containerPort: 9005
---
apiVersion: v1
kind: Service
metadata:
  name: movie
  namespace: @k8s.namespace@
  labels: 
    app: movie
spec:
  type: NodePort
  selector:
    app: movie
  ports:
  - port: 9005
    targetPort: 9005
    nodePort: 31070

