apiVersion: v1
kind: ReplicationController
metadata:
  name: configserver
  namespace: @k8s.namespace@
spec:
  replicas: @spec.replicas@
  selector:
    app: configserver
  template:
    metadata:
      name: configserver
      labels:
        app: configserver
    spec:
      containers:
      - name: configserver
        image: @docker.image.prefix@/config-microservice
        ports:
        - containerPort: 8888
---
apiVersion: v1
kind: Service
metadata:
  name: configserver
  namespace: @k8s.namespace@
  labels: 
    app: configserver
spec:
  type: NodePort
  selector:
    app: configserver
  ports:
  - port: 8888
    targetPort: 8888
    nodePort: 31020

