apiVersion: v1
kind: ReplicationController
metadata:
  name: users
  namespace: @k8s.namespace@
spec:
  replicas: @spec.replicas@
  selector:
    app: users
  template:
    metadata:
      name: users
      labels:
        app: users
    spec:
      containers:
      - name: users
        image: @docker.image.prefix@/users-microservice
        resources:
          requests:
            cpu: 400m
        ports:
        - containerPort: 9000
---
apiVersion: v1
kind: Service
metadata:
  name: users
  namespace: @k8s.namespace@
  labels: 
    app: users
spec:
  type: NodePort
  selector:
    app: users
  ports:
  - port: 9000
    targetPort: 9000
    nodePort: 31060

