apiVersion: v1
kind: ReplicationController
metadata:
  name: discovery
  namespace: @k8s.namespace@
spec:
  replicas: @spec.replicas@
  selector:
    app: discovery
  template:
    metadata:
      name: discovery
      labels:
        app: discovery
    spec:
      containers:
      - name: discovery
        image: @docker.image.prefix@/discovery-microservice
        ports:
        - containerPort: 8761
---
apiVersion: v1
kind: Service
metadata:
  name: discovery
  namespace: @k8s.namespace@
  labels: 
    app: discovery
spec:
  type: NodePort
  selector:
    app: discovery
  ports:
  - port: 8761
    targetPort: 8761
    nodePort: 30010

